<?php

/**
 * MUserTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MUser');
    }
}