<?php

/**
 * TFollowTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TFollowTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TFollowTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TFollow');
    }
}