<?php

/**
 * TRetweetTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TRetweetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TRetweetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TRetweet');
    }
}