<?php

/**
 * TTweetTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TTweetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TTweetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TTweet');
    }
}