<?php

/**
 * TUserProfileTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TUserProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TUserProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TUserProfile');
    }
}