<?php

/**
 * BaseTFollow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $follow_user_id
 * @property sfGuardUser $sfGuardUser
 *
 * @method integer     getUserId()         Returns the current record's "user_id" value
 * @method integer     getFollowUserId()   Returns the current record's "follow_user_id" value
 * @method sfGuardUser getSfGuardUser()    Returns the current record's "sfGuardUser" value
 * @method TFollow     setUserId()         Sets the current record's "user_id" value
 * @method TFollow     setFollowUserId()   Sets the current record's "follow_user_id" value
 * @method TFollow     setSfGuardUser()    Sets the current record's "sfGuardUser" value
 * 
 * @package    nowtter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTFollow extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_follow');
        $this->hasColumn('user_id', 'integer', null, array(
            'type' => 'integer',
            'primary' => true,
        ));
        $this->hasColumn('follow_user_id', 'integer', null, array(
            'type' => 'integer',
            'primary' => true,
        ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
            'local' => 'user_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}