<?php

/**
 * BaseTUserProfile
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $user_id
 * @property string $display_name
 * @property string $profile
 * @property date $birthday
 * @property boolean $is_private
 * @property sfGuardUser $sfGuardUser
 *
 * @method integer      getUserId()       Returns the current record's "user_id" value
 * @method string       getDisplayName()  Returns the current record's "display_name" value
 * @method string       getProfile()      Returns the current record's "profile" value
 * @method date         getBirthday()     Returns the current record's "birthday" value
 * @method boolean      getIsPrivate()    Returns the current record's "is_private" value
 * @method sfGuardUser  getSfGuardUser()  Returns the current record's "sfGuardUser" value
 * @method TUserProfile setUserId()       Sets the current record's "user_id" value
 * @method TUserProfile setDisplayName()  Sets the current record's "display_name" value
 * @method TUserProfile setProfile()      Sets the current record's "profile" value
 * @method TUserProfile setBirthday()     Sets the current record's "birthday" value
 * @method TUserProfile setIsPrivate()    Sets the current record's "is_private" value
 * @method TUserProfile setSfGuardUser()  Sets the current record's "sfGuardUser" value
 *
 * @package    nowtter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_user_profile');
        $this->hasColumn('user_id', 'integer', null, array(
            'type' => 'integer',
            'notnull' => true,
        ));
        $this->hasColumn('display_name', 'string', 255, array(
            'type' => 'string',
            'notnull' => 'ture',
            'unique' => true,
            'length' => 255,
        ));
        $this->hasColumn('profile', 'string', 1000, array(
            'type' => 'string',
            'length' => 1000,
        ));
        $this->hasColumn('birthday', 'date', null, array(
            'type' => 'date',
        ));
        $this->hasColumn('is_private', 'boolean', null, array(
            'type' => 'boolean',
            'notnull' => true,
            'default' => 0,
        ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
            'local' => 'user_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}