<?php

/**
 * BaseTFavorite
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $user_id
 * @property integer $tweet_id
 * @property MUser $MUser
 * @property TTweet $TTweet
 *
 * @method integer   getUserId()   Returns the current record's "user_id" value
 * @method integer   getTweetId()  Returns the current record's "tweet_id" value
 * @method MUser     getMUser()    Returns the current record's "MUser" value
 * @method TTweet    getTTweet()   Returns the current record's "TTweet" value
 * @method TFavorite setUserId()   Sets the current record's "user_id" value
 * @method TFavorite setTweetId()  Sets the current record's "tweet_id" value
 * @method TFavorite setMUser()    Sets the current record's "MUser" value
 * @method TFavorite setTTweet()   Sets the current record's "TTweet" value
 *
 * @package    nowtter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTFavorite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_favorite');
        $this->hasColumn('user_id', 'integer', null, array(
            'type' => 'integer',
            'notnull' => true,
        ));
        $this->hasColumn('tweet_id', 'integer', null, array(
            'type' => 'integer',
            'notnull' => true,
        ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MUser', array(
            'local' => 'user_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE'));

        $this->hasOne('TTweet', array(
            'local' => 'tweet_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}