# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
post:
  url: /post
  param: { module: post, action: post }

postjson:
  url: /post/json
  param: { module: post, action: postJson }

getjson:
  url: /timeline/json
  param: { module: timeline, action: getJson }

homepage:
  url:   /
  param: { module: timeline, action: index }

timeline:
  url: /:name
  param: { module: timeline, action: index }



# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
