TUserProfile:
  actAs:
    { Timestampable: ~ }
  columns:
    user_id: { type: integer, notnull: true }
    display_name: { type: string(255) ,notnull: ture , unique: true}
    profile: { type: string(1000) }
    birthday: { type: date }
    is_private: { type: boolean ,notnull: true, default: 0}
  relations:
    sfGuardUser: { onDelete: CASCADE, local: user_id, foreign: id, foreignType: one }

TTweet:
  actAs:
    { Timestampable: ~ }
  columns:
    user_id: { type: integer, notnull: true }
    body: { type: string(140), notnull: true }
    is_enable: { type: boolean, notnull: true, default: 1 }
  relations:
    sfGuardUser: { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: Tweets }

TFollow:
  actAs:
    { Timestampable: ~ }
  columns:
    user_id: { type: integer ,primary: true}
    follow_user_id: { type: integer , primary: true }
  relations:
    sfGuardUser: { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: Follows }

TFavorite:
  actAs:
    { Timestampable: ~ }
  columns:
    user_id: { type: integer, notnull: true }
    tweet_id: { type: integer, notnull: true }
  relations:
    sfGuardUser: { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: Favorites }
    TTweet: { onDelete: CASCADE, local: tweet_id, foreign: id, foreignAlias: FavoritedUsers }

TRetweet:
  actAs:
    { Timestampable: ~ }
  columns:
    user_id: { type: integer, notnull: true }
    tweet_id: { type: integer, notnull: true }
  relations:
    sfGuardUser: { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: Retweets }
    TTweet: { onDelete: CASCADE, local: tweet_id, foreign: id, foreignAlias: RetweetedUsers }
